"""
scripts/train_all.py
=======================
Block 2 pipeline runner: trains all model variants on the processed patch
dataset from Block 1, logs metrics, and saves artefacts to reports/.

Models trained:
  1. CustomCNN          (DFSAR-only, 2-channel input)
  2. IceResNet (scratch) (DFSAR-only, 2-channel input, trained from scratch)
  3. IceResNet (pretrained) (DFSAR-only, 2-channel, ImageNet-adapted)

Loss:
  Weighted BCE with pos_weight derived from the class_balance.txt report
  generated by Block 1.  Falls back to focal loss if the imbalance ratio
  exceeds 10:1 (see select_loss()).

Artefacts saved to reports/:
  - {model_name}_loss_curve.png
  - {model_name}_confusion_matrix.png
  - {model_name}_roc_curve.png
  - training_summary.txt   (all metrics in one table)
  - models/{model_name}.pth (best checkpoint by val F1)

Usage:
    python -m scripts.train_all
"""

import os, sys, time, json
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("Agg")   # headless backend — no display required
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, roc_curve,
)

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from src.datasets.ice_dataset import IcePatchDataset
from src.models.custom_cnn import CustomCNN
from src.models.resnet import IceResNet

# ── Paths ──────────────────────────────────────────────────────────────────────
PROCESSED_DIR = "data/processed"
REPORTS_DIR   = "reports"
MODELS_DIR    = "models"
os.makedirs(REPORTS_DIR, exist_ok=True)
os.makedirs(MODELS_DIR,  exist_ok=True)

# ── Hyper-parameters ───────────────────────────────────────────────────────────
BATCH_SIZE = 16
EPOCHS     = 3           # reduced to 3 for faster CPU demo; increase to 30-50 with GPU or real data
LR         = 1e-3
SEED       = 42
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

torch.manual_seed(SEED)
np.random.seed(SEED)


# ──────────────────────────────────────────────────────────────────────────────
# Focal Loss (alternative to weighted BCE when imbalance > 10:1)
# ──────────────────────────────────────────────────────────────────────────────
class FocalLoss(nn.Module):
    """
    Focal Loss for binary classification.
    Lin et al., "Focal Loss for Dense Object Detection", 2017.

    gamma=2 is the standard recommendation.  When gamma=0 this reduces to BCE.
    Focal loss down-weights easy negatives (non-ice) so the model focuses
    on hard-to-classify minority (ice) patches.

    Viva note: we prefer this over pure pos_weight when imbalance > 10:1
    because pos_weight still assigns full gradient to each non-ice sample;
    focal loss additionally suppresses well-classified non-ice gradients.
    """
    def __init__(self, alpha=0.25, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        bce = nn.functional.binary_cross_entropy_with_logits(
            logits, targets, reduction="none"
        )
        p_t = torch.exp(-bce)
        focal = self.alpha * (1 - p_t) ** self.gamma * bce
        return focal.mean()


def select_loss(pos_weight_val: float):
    """Return an appropriate loss function given the positive class weight."""
    if pos_weight_val > 10.0:
        print(f"  Imbalance ratio {pos_weight_val:.1f} > 10 -> using Focal Loss (gamma=2)")
        return FocalLoss(alpha=0.25, gamma=2.0)
    else:
        pw = torch.tensor([pos_weight_val], dtype=torch.float32).to(DEVICE)
        print(f"  Imbalance ratio {pos_weight_val:.1f} ≤ 10 -> using BCEWithLogitsLoss(pos_weight={pos_weight_val:.2f})")
        return nn.BCEWithLogitsLoss(pos_weight=pw)


# ──────────────────────────────────────────────────────────────────────────────
# Data loading
# ──────────────────────────────────────────────────────────────────────────────
def load_split(name):
    """Load a processed .npz split produced by ingest_and_split.py."""
    path = os.path.join(PROCESSED_DIR, f"{name}.npz")
    if not os.path.isfile(path):
        raise FileNotFoundError(
            f"Processed split '{path}' not found. "
            "Run `python -m scripts.ingest_and_split` first."
        )
    data = np.load(path)
    patches = list(zip(
        data["images"],     # (C, H, W) float32 arrays
        data["labels"].tolist(),
        [tuple(c) for c in data["coords"]],
    ))
    return patches


def read_pos_weight() -> float:
    """Parse pos_weight from the class_balance.txt report."""
    path = os.path.join(REPORTS_DIR, "class_balance.txt")
    if not os.path.isfile(path):
        print("  WARNING: class_balance.txt not found, defaulting pos_weight=5.0")
        return 5.0
    with open(path) as f:
        for line in f:
            if "pos_weight for BCE" in line:
                return float(line.split(":")[1].strip().split()[0])
    return 5.0


# ──────────────────────────────────────────────────────────────────────────────
# Evaluation helper
# ──────────────────────────────────────────────────────────────────────────────
def evaluate(model, loader):
    model.eval()
    all_logits, all_labels = [], []
    with torch.no_grad():
        for x, y in loader:
            x = x.to(DEVICE)
            logits = model(x).cpu()
            all_logits.append(logits)
            all_labels.append(y)
    logits  = torch.cat(all_logits).numpy().flatten()
    labels  = torch.cat(all_labels).numpy().flatten()
    probs   = 1 / (1 + np.exp(-logits))   # sigmoid
    preds   = (probs >= 0.5).astype(int)
    metrics = {
        "accuracy":  accuracy_score(labels, preds),
        "precision": precision_score(labels, preds, zero_division=0),
        "recall":    recall_score(labels, preds, zero_division=0),
        "f1":        f1_score(labels, preds, zero_division=0),
    }
    try:
        metrics["roc_auc"] = roc_auc_score(labels, probs)
    except ValueError:
        metrics["roc_auc"] = float("nan")
    metrics["cm"]     = confusion_matrix(labels, preds, labels=[0, 1])
    metrics["probs"]  = probs
    metrics["labels"] = labels
    return metrics


# ──────────────────────────────────────────────────────────────────────────────
# Plot helpers
# ──────────────────────────────────────────────────────────────────────────────
def save_loss_curve(train_losses, val_losses, name):
    plt.figure()
    plt.plot(train_losses, label="Train Loss")
    plt.plot(val_losses,   label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(f"{name} — Loss Curve")
    plt.legend()
    path = os.path.join(REPORTS_DIR, f"{name}_loss_curve.png")
    plt.savefig(path, dpi=120)
    plt.close()
    return path


def save_confusion_matrix(cm, name):
    disp = ConfusionMatrixDisplay(cm, display_labels=["Non-Ice", "Ice"])
    disp.plot(cmap=plt.cm.Blues)
    plt.title(f"{name} — Confusion Matrix")
    path = os.path.join(REPORTS_DIR, f"{name}_confusion_matrix.png")
    plt.savefig(path, dpi=120)
    plt.close()
    return path


def save_roc_curve(labels, probs, name):
    if np.isnan(probs).any() or len(np.unique(labels)) < 2:
        return None
    fpr, tpr, _ = roc_curve(labels, probs)
    auc_val = roc_auc_score(labels, probs)
    plt.figure()
    plt.plot(fpr, tpr, label=f"AUC = {auc_val:.3f}")
    plt.plot([0,1],[0,1],"--", color="grey")
    plt.xlabel("FPR"); plt.ylabel("TPR")
    plt.title(f"{name} — ROC Curve")
    plt.legend()
    path = os.path.join(REPORTS_DIR, f"{name}_roc_curve.png")
    plt.savefig(path, dpi=120)
    plt.close()
    return path


# ──────────────────────────────────────────────────────────────────────────────
# Core training loop
# ──────────────────────────────────────────────────────────────────────────────
def train_model(model, train_loader, val_loader, criterion, name):
    """Train one model; return (best_val_metrics, train_losses, val_losses, train_time)."""
    param_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"\n{'='*60}")
    print(f"  Training: {name}  ({param_count:,} trainable params)")
    print(f"  Device  : {DEVICE}")
    print(f"{'='*60}")

    optimizer = optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()), lr=LR
    )
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="max", patience=5, factor=0.5
    )

    train_losses, val_losses = [], []
    best_val_f1   = -1.0
    best_ckpt     = os.path.join(MODELS_DIR, f"{name}.pth")
    best_metrics  = {}
    t0 = time.time()

    for epoch in range(EPOCHS):
        # ── Training ──
        model.train()
        epoch_loss = 0.0
        for x, y in train_loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            optimizer.zero_grad()
            loss = criterion(model(x), y)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item() * x.size(0)
        avg_train = epoch_loss / max(len(train_loader.dataset), 1)
        train_losses.append(avg_train)

        # ── Validation ──
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(DEVICE), y.to(DEVICE)
                val_loss += criterion(model(x), y).item() * x.size(0)
        avg_val = val_loss / max(len(val_loader.dataset), 1)
        val_losses.append(avg_val)

        # ── Quick metrics for scheduler ──
        val_metrics = evaluate(model, val_loader)
        scheduler.step(val_metrics["f1"])

        if val_metrics["f1"] > best_val_f1:
            best_val_f1  = val_metrics["f1"]
            best_metrics = val_metrics
            torch.save(model.state_dict(), best_ckpt)

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(
                f"  Ep {epoch+1:3d}/{EPOCHS} | "
                f"Train {avg_train:.4f} | Val {avg_val:.4f} | "
                f"F1 {val_metrics['f1']:.3f} | AUC {val_metrics['roc_auc']:.3f}"
            )

    train_time = time.time() - t0
    print(f"  Done in {train_time:.1f}s  |  Best val F1={best_val_f1:.3f}")
    return best_metrics, train_losses, val_losses, train_time, param_count


# ──────────────────────────────────────────────────────────────────────────────
# Circularity / near-perfect-accuracy flag
# ──────────────────────────────────────────────────────────────────────────────
def flag_suspicious_metrics(metrics, name):
    """
    Emit a visible WARNING if metrics look suspiciously perfect.
    Near-perfect accuracy on a label-threshold-derived dataset is a major
    red flag: the model may simply be re-learning the CPR>1 / DOP<0.13
    threshold rather than capturing spatial texture.  See PRD §11 (Label
    Circularity risk).
    """
    acc = metrics.get("accuracy", 0)
    f1  = metrics.get("f1", 0)
    if acc > 0.97 or f1 > 0.97:
        msg = (
            f"\n[WARNING] SUSPICIOUS PERFORMANCE: {name}\n"
            f"   accuracy={acc:.3f}, F1={f1:.3f}\n"
            "   This may indicate label circularity: the model could be\n"
            "   re-learning the CPR>1 AND DOP<0.13 threshold rule rather\n"
            "   than learning spatial/textural features.\n"
            "   -> Inspect Grad-CAM (Block 3) and check if attention focuses\n"
            "     on physically plausible spatial structures beyond single pixels.\n"
            "   -> Report this limitation explicitly in viva and report.\n"
        )
        print(msg)
        return msg
    return ""


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────
def main():
    # 1. Load data
    print("Loading processed splits from data/processed/ …")
    train_patches = load_split("train")
    val_patches   = load_split("val")
    test_patches  = load_split("test")

    train_ds = IcePatchDataset(train_patches, augment=True,  normalize=True)
    val_ds   = IcePatchDataset(val_patches,   augment=False, normalize=True)
    test_ds  = IcePatchDataset(test_patches,  augment=False, normalize=True)

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    # 2. Loss function
    pos_weight_val = read_pos_weight()
    criterion = select_loss(pos_weight_val)

    # 3. Define model variants
    in_channels = train_ds[0][0].shape[0]  # 2 for DFSAR-only
    print(f"\nDetected input channels: {in_channels}")

    model_defs = [
        ("CustomCNN",         CustomCNN(in_channels=in_channels, num_classes=1)),
        ("ResNet_scratch",    IceResNet(in_channels=in_channels, num_classes=1, pretrained=False)),
        ("ResNet_pretrained", IceResNet(in_channels=in_channels, num_classes=1, pretrained=True)),
    ]

    summary_rows = []
    circularity_flags = []

    # 4. Train each model
    for name, model in model_defs:
        model = model.to(DEVICE)
        best_metrics, train_losses, val_losses, train_time, params = train_model(
            model, train_loader, val_loader, criterion, name
        )

        # Reload best checkpoint and evaluate on test set
        model.load_state_dict(torch.load(os.path.join(MODELS_DIR, f"{name}.pth"), map_location=DEVICE))
        test_metrics = evaluate(model, test_loader)

        flag = flag_suspicious_metrics(test_metrics, name)
        if flag:
            circularity_flags.append(flag)

        # Save plots
        save_loss_curve(train_losses, val_losses, name)
        save_confusion_matrix(test_metrics["cm"], name)
        save_roc_curve(test_metrics["labels"], test_metrics["probs"], name)

        row = {
            "model":       name,
            "accuracy":    test_metrics["accuracy"],
            "precision":   test_metrics["precision"],
            "recall":      test_metrics["recall"],
            "f1":          test_metrics["f1"],
            "roc_auc":     test_metrics["roc_auc"],
            "params":      params,
            "train_time":  round(train_time, 1),
        }
        summary_rows.append(row)

        print(f"\n  Test metrics — {name}:")
        for k, v in row.items():
            if k not in ("model", "params", "train_time"):
                print(f"    {k:12s}: {v:.4f}")
        print(f"    params      : {params:,}")
        print(f"    train_time  : {train_time:.1f}s")

    # 5. Save summary
    with open(os.path.join(REPORTS_DIR, "training_summary.json"), "w") as f:
        json.dump(summary_rows, f, indent=2)

    summary_md = (
        "# Training Summary\n\n"
        "> **DATA SOURCE:** SYNTHETIC (physically-motivated SAR scene — "
        "no real DFSAR tiles from PRADAN yet). "
        "Numbers below demonstrate pipeline correctness only, "
        "NOT real ice-detection performance.\n\n"
        "| Model | Accuracy | Precision | Recall | F1 | ROC-AUC | Params | Time (s) |\n"
        "|-------|----------|-----------|--------|----|---------|--------|----------|\n"
    )
    for r in summary_rows:
        summary_md += (
            f"| {r['model']} | {r['accuracy']:.4f} | {r['precision']:.4f} | "
            f"{r['recall']:.4f} | {r['f1']:.4f} | {r['roc_auc']:.4f} | "
            f"{r['params']:,} | {r['train_time']} |\n"
        )
    if circularity_flags:
        summary_md += "\n## [WARNING] Circularity / Near-Perfect Accuracy Flags\n\n"
        for flag in circularity_flags:
            summary_md += flag + "\n"

    with open(os.path.join(REPORTS_DIR, "training_summary.md"), "w") as f:
        f.write(summary_md)

    print(f"\nAll results saved to {REPORTS_DIR}/")
    print("Block 2 complete.")
    return summary_rows   # so Block 3 can read them in-process if needed


if __name__ == "__main__":
    main()
